In [139]:
import numpy as np
import pandas as pd

In [140]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns = ['cgpa', 'profile_score', 'lpa'])

In [141]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [142]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):

    parameters['W'+ str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b'+ str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [143]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [144]:
def linear_forward(A_prev,W,b):
  Z = np.dot(W.T , A_prev) + b # Z=W**T*Aprev​+b ,for first hidden neuron - z1​=w11​x1​+w21​x2​+b1
  return Z

In [145]:
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2    # number of layers in the NN

    for l in range(1, L+1):

        A_prev = A

        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]

        #print("A" + str(l-1) + ": ", A_prev)
        #print("W" + str(l) + ": ", W1)
        #print("b" + str(l) + ": ", b1)
        #print("-"*20)

        A = linear_forward(A_prev, W1, b1)

        #print("A" + str(l) + ": ", A)

    return A, A_prev


In [146]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

#parameters initilization
parameters = initialize_parameters([2,2,1])

L_layer_forward(X,parameters)

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [147]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0])

In [148]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

#parameters initilization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [149]:
y_hat = y_hat[0][0]

In [150]:
A1

array([[1.6],
       [1.6]])

In [151]:
update_parameters(parameters, y,y_hat,A1,X)

In [152]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10740404, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.        ]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [153]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)

In [154]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_1825/1064948781.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat)*A1[0][0])
/tmp/ipykernel_1825/1064948781.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat)*A1[1][0])
/tmp/ipykernel_1825/1064948781.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.0

In [155]:
print(parameters["W1"].shape)
print(parameters["b1"].shape)

print(parameters["W2"].shape)
print(parameters["b2"].shape)

print(y_hat.shape)

(2, 2)
(2, 1)
(2, 1)
(1, 1)
(1, 1)


In [156]:
#epoch implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa','profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]

      #parameter initialization

    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append((y-y_hat)**2)

  print('Epoch - ', i+1, 'Loss - ', np.array(Loss).mean())

parameters

Epoch -  1 Loss -  26.254013052428576
Epoch -  2 Loss -  19.267750624390345
Epoch -  3 Loss -  9.836870612679967
Epoch -  4 Loss -  3.1855454286975786
Epoch -  5 Loss -  1.2636008240889451


{'W1': array([[0.27272117, 0.39830172],
        [0.31418327, 0.41851924]]),
 'b1': array([[0.02873672],
        [0.        ]]),
 'W2': array([[0.43320711],
        [0.49309881]]),
 'b2': array([[0.11709707]])}