In [130]:
import numpy as np
import pandas as pd

In [131]:
from sklearn.datasets import make_regression
X, y = make_regression(
    n_samples=75,
    n_features=2,
    noise=10,
    random_state=42
)

In [132]:
cgpa = 4 + (X[:, 0] - X[:, 0].min()) / (X[:, 0].max() - X[:, 0].min()) * 6      
profile_score = 40 + (X[:, 1] - X[:, 1].min()) / (X[:, 1].max() - X[:, 1].min()) * 60  
lpa = 1 + (y - y.min()) / (y.max() - y.min()) * 9 

In [133]:
df = pd.DataFrame({
    'cgpa': cgpa,
    'profile_score': profile_score,
    'lpa': lpa
})

In [134]:
df

,cgpa,profile_score,lpa
0,7.371300,67.829786,4.971321
1,5.921378,51.915326,1.245881
2,5.915972,61.694191,2.651913
3,8.752759,79.696223,8.538477
4,6.910396,84.717218,6.976188
...,...,...,...
70,6.051544,68.713188,3.756792
71,8.768798,62.641104,6.165574
72,7.410788,68.632539,5.721305
73,7.693037,90.101538,8.967541


In [135]:
# Normalize features 
df['cgpa'] = (df['cgpa'] - df['cgpa'].mean()) / df['cgpa'].std()
df['profile_score'] = (df['profile_score'] - df['profile_score'].mean()) / df['profile_score'].std()

In [136]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):

    parameters['W'+ str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b'+ str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [137]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [138]:
def linear_forward(A_prev,W,b):
  Z = np.dot(W.T , A_prev) + b # Z=W**T*Aprev​+b ,for first hidden neuron - z1​=w11​x1​+w21​x2​+b1
  return Z

In [139]:
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2    # number of layers in the NN

    for l in range(1, L+1):

        A_prev = A

        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]

        #print("A" + str(l-1) + ": ", A_prev)
        #print("W" + str(l) + ": ", W1)
        #print("b" + str(l) + ": ", b1)
        #print("-"*20)

        A = linear_forward(A_prev, W1, b1)

        #print("A" + str(l) + ": ", A)

    return A, A_prev


In [140]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

#parameters initilization
parameters = initialize_parameters([2,2,1])

L_layer_forward(X,parameters)

(array([[0.00203872]]),
 array([[0.0101936],
        [0.0101936]]))

In [141]:
def update_parameters(parameters, y, y_hat, A1, X):
    W2_old = parameters['W2'].copy()

    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y-y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat)*W2_old[0][0]*X[0][0])
    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat)*W2_old[0][0]*X[1][0])   
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y-y_hat)*W2_old[0][0])

    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat)*W2_old[1][0]*X[0][0])   
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y-y_hat)*W2_old[1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y-y_hat)*W2_old[1][0])

In [142]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

#parameters initilization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [143]:
y_hat = y_hat[0][0]

In [144]:
A1

array([[0.0101936],
       [0.0101936]])

In [145]:
update_parameters(parameters, y,y_hat,A1,X)

In [146]:
parameters

{'W1': array([[0.1005309 , 0.1005309 ],
        [0.09957041, 0.09957041]]),
 'b1': array([[0.00099386],
        [0.00099386]]),
 'W2': array([[0.10010131],
        [0.10010131]]),
 'b2': array([[0.00993856]])}

In [147]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)

In [148]:
update_parameters(parameters,y,y_hat,A1,X)

C:\Users\PC\AppData\Local\Temp\ipykernel_9644\16383275.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat)*A1[0][0])
C:\Users\PC\AppData\Local\Temp\ipykernel_9644\16383275.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat)*A1[1][0])
C:\Users\PC\AppData\Local\Temp\ipykernel_9644\16383275.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecat

In [149]:
print(parameters["W1"].shape)
print(parameters["b1"].shape)

print(parameters["W2"].shape)
print(parameters["b2"].shape)

print(y_hat.shape)

(2, 2)
(2, 1)
(2, 1)
(1, 1)
(1, 1)


In [150]:
#epoch implementation
parameters = initialize_parameters([2,2,1])
epochs = 100

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa','profile_score']].values[j].reshape(2,1)
        y = df[['lpa']].values[j][0]

        y_hat, A1 = L_layer_forward(X, parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters, y, y_hat, A1, X)
        Loss.append((y-y_hat)**2)

    print('Epoch - ', i+1, 'Loss - ', np.array(Loss).mean())

parameters

Epoch -  1 Loss -  27.431934569124437
Epoch -  2 Loss -  20.827213396350906
Epoch -  3 Loss -  14.222121963598154
Epoch -  4 Loss -  7.217023475098925
Epoch -  5 Loss -  2.1847627182781837
Epoch -  6 Loss -  0.40879729714264956
Epoch -  7 Loss -  0.09018456252836234
Epoch -  8 Loss -  0.05198974468684151
Epoch -  9 Loss -  0.04798604599448513
Epoch -  10 Loss -  0.04753373404625126
Epoch -  11 Loss -  0.047462844979816544
Epoch -  12 Loss -  0.04744429432598851
Epoch -  13 Loss -  0.04743715214976344
Epoch -  14 Loss -  0.047433855368239734
Epoch -  15 Loss -  0.04743220600940404
Epoch -  16 Loss -  0.04743134598987048
Epoch -  17 Loss -  0.04743088595430254
Epoch -  18 Loss -  0.04743063475415738
Epoch -  19 Loss -  0.0474304943627612
Epoch -  20 Loss -  0.047430413273704466
Epoch -  21 Loss -  0.04743036406313367
Epoch -  22 Loss -  0.04743033202658084
Epoch -  23 Loss -  0.04743030925113524
Epoch -  24 Loss -  0.04743029147121721
Epoch -  25 Loss -  0.04743027638574203
Epoch -  26 L

{'W1': array([[0.62652269, 0.62652269],
        [0.62547975, 0.62547975]]),
 'b1': array([[1.01234357],
        [1.01234357]]),
 'W2': array([[1.33776023],
        [1.33776023]]),
 'b2': array([[2.33222096]])}