In [5]:
from sklearn.datasets import make_regression
import numpy as np
import pandas as pd

In [6]:
X, y = make_regression(n_samples=75, n_features=2, noise=10, random_state=42)

cgpa = 4 + (X[:, 0] - X[:, 0].min()) / (X[:, 0].max() - X[:, 0].min()) * 6
profile_score = 40 + (X[:, 1] - X[:, 1].min()) / (X[:, 1].max() - X[:, 1].min()) * 60
lpa = 1 + (y - y.min()) / (y.max() - y.min()) * 9


In [7]:
df = pd.DataFrame({'cgpa': cgpa, 'profile_score': profile_score, 'lpa': lpa})

df['cgpa'] = (df['cgpa'] - df['cgpa'].mean()) / df['cgpa'].std()
df['profile_score'] = (df['profile_score'] - df['profile_score'].mean()) / df['profile_score'].std()

df

,cgpa,profile_score,lpa
0,0.534185,-0.432249,4.971321
1,-0.545939,-1.778404,1.245881
2,-0.549966,-0.951240,2.651913
3,1.563308,0.571495,8.538477
4,0.190834,0.996206,6.976188
...,...,...,...
70,-0.448971,-0.357525,3.756792
71,1.575257,-0.871144,6.165574
72,0.563602,-0.364347,5.721305
73,0.773865,1.451648,8.967541


In [8]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [9]:
model = Sequential()

model.add(Dense(2,activation = 'linear', input_dim = 2))
model.add(Dense(1,activation = 'linear'))

C:\Users\PC\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.get_weights()

[array([[ 0.05450094, -0.68936956],
        [ 0.07587636, -0.66151434]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.06688702],
        [ 0.577924  ]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights = [np.array([[0.1,0.1], [0.1 , 0.1]], dtype = np.float32),
               np.array([0.,0.],dtype = np.float32),
               np.array([[0.1],[0.1]],dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [13]:
model.set_weights(new_weights)

In [14]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [16]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs = 75 , verbose = 1, batch_size = 1)

Epoch 1/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 30.5272  
Epoch 2/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - loss: 29.4557
Epoch 3/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - loss: 28.1344
Epoch 4/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - loss: 26.5188
Epoch 5/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - loss: 24.6174
Epoch 6/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - loss: 22.4476
Epoch 7/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - loss: 20.1153
Epoch 8/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - loss: 17.6527
Epoch 9/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - loss: 15.1959
Epoch 10/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - loss: 12.7561
Epoch 11/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.5103  
Epoch 12/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - loss: 8.4229 
Epoch 13/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - loss: 6.5655
Epoch 14/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4.9822  
Epoch 15/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 973

In [17]:
model.get_weights()

[array([[0.6355275 , 0.6355275 ],
        [0.63998026, 0.63998026]], dtype=float32),
 array([1.5538393, 1.5538393], dtype=float32),
 array([[1.3067946],
        [1.3067946]], dtype=float32),
 array([0.966463], dtype=float32)]