In [1]:
from sklearn.datasets import make_regression
import numpy as np
import pandas as pd

In [2]:
X, y = make_regression(n_samples=75, n_features=2, noise=10, random_state=42)

Feature1 = 4 + (X[:, 0] - X[:, 0].min()) / (X[:, 0].max() - X[:, 0].min()) * 6
Feature2 = 40 + (X[:, 1] - X[:, 1].min()) / (X[:, 1].max() - X[:, 1].min()) * 60
target = 1 + (y - y.min()) / (y.max() - y.min()) * 9


In [3]:
df = pd.DataFrame({'Feature1': Feature1, 'Feature2': Feature2, 'target': target})

df['Feature1'] = (df['Feature1'] - df['Feature1'].mean()) / df['Feature1'].std()
df['Feature2'] = (df['Feature2'] - df['Feature2'].mean()) / df['Feature2'].std()

df

,Feature1,Feature2,target
0,0.534185,-0.432249,4.971321
1,-0.545939,-1.778404,1.245881
2,-0.549966,-0.951240,2.651913
3,1.563308,0.571495,8.538477
4,0.190834,0.996206,6.976188
...,...,...,...
70,-0.448971,-0.357525,3.756792
71,1.575257,-0.871144,6.165574
72,0.563602,-0.364347,5.721305
73,0.773865,1.451648,8.967541


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2,activation = 'linear', input_dim = 2))
model.add(Dense(1,activation = 'linear'))

C:\Users\PC\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[ 0.313766  ,  0.222422  ],
        [ 0.49179995, -0.5936262 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.04446995],
        [ 0.70661175]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1,0.1], [0.1 , 0.1]], dtype = np.float32),
               np.array([0.,0.],dtype = np.float32),
               np.array([[0.1],[0.1]],dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values,df['target'].values,epochs = 75 , verbose = 1, batch_size = 1)

Epoch 1/75


75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 30.5804 
Epoch 2/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 29.5522  
Epoch 3/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 28.2360  
Epoch 4/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 26.6565  
Epoch 5/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 24.7450  
Epoch 6/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 22.5991  
Epoch 7/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20.2653
Epoch 8/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 17.7979  
Epoch 9/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.3434
Epoch 10/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12.9211  
Epoch 11/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.6444
Epoch 12/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.5378  
Epoch 13/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6959  
Epoch 14/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5.0818  
Epoch 15/75
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3.755

In [13]:
model.get_weights()

[array([[0.6389471 , 0.6389471 ],
        [0.64177924, 0.64177924]], dtype=float32),
 array([1.555299, 1.555299], dtype=float32),
 array([[1.3099989],
        [1.3099989]], dtype=float32),
 array([0.9653229], dtype=float32)]