In [1]:
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [2]:
X, y = make_classification(
    n_samples=75,
    n_features=2,
    n_redundant=0,
    n_informative=2,
    n_clusters_per_class=1,
    random_state=42
)

cgpa = 4 + (X[:,0] - X[:,0].min()) / (X[:,0].max() - X[:,0].min()) * 6
profile_score = 40 + (X[:,1] - X[:,1].min()) / (X[:,1].max() - X[:,1].min()) * 60

In [3]:
df = pd.DataFrame({
    "cgpa": cgpa,
    "profile_score": profile_score,
    "placed": y
})

df["cgpa"] = (df["cgpa"] - df["cgpa"].mean()) / df["cgpa"].std()
df["profile_score"] = (
    (df["profile_score"] - df["profile_score"].mean())
    / df["profile_score"].std()
)

df.head()

,cgpa,profile_score,placed
0,0.375501,-0.121659,1
1,0.263947,-1.814197,0
2,0.021507,-1.314660,0
3,-0.733024,0.144970,0
4,0.850220,1.130199,1


In [4]:
model = Sequential()

model.add(Dense(2,activation="sigmoid",input_dim=2))
model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
new_weights = [
    np.array([[0.1,0.1],
              [0.1,0.1]], dtype=np.float32),

    np.array([0.,0.], dtype=np.float32),

    np.array([[0.1],
              [0.1]], dtype=np.float32),

    np.array([0.], dtype=np.float32)
]

model.set_weights(new_weights)

In [7]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
optimizer = keras.optimizers.Adam(learning_rate=0.3)

model.compile(loss="binary_crossentropy",optimizer=optimizer,metrics=["accuracy"])

In [9]:
history = model.fit(df.iloc[:,0:-1].values,df["placed"].values,epochs=100,batch_size=1,verbose=1)

Epoch 1/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4800 - loss: 0.7428
Epoch 2/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.4267 - loss: 0.7642
Epoch 3/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4400 - loss: 0.7309
Epoch 4/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8267 - loss: 0.4105
Epoch 5/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9333 - loss: 0.2894
Epoch 6/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9200 - loss: 0.2513
Epoch 7/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9600 - loss: 0.1982
Epoch 8/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9600 - loss: 0.1792
Epoch 9/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9600 - loss: 0.1916
Epoch 10/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9600 - loss: 0.2092
Epoch 11/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9467 - loss: 0.2040
Epoch 12/100
75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy:

In [10]:
model.get_weights()

[array([[-24.83506  , -24.83506  ],
        [ -9.2436495,  -9.2436495]], dtype=float32),
 array([-0.87831813, -0.87831813], dtype=float32),
 array([[-5.155705],
        [-5.155705]], dtype=float32),
 array([8.447641], dtype=float32)]