In [11]:
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [12]:
X, y = make_classification(
    n_samples=75,
    n_features=2,
    n_redundant=0,
    n_informative=2,
    n_clusters_per_class=1,
    random_state=42
)

Feature1 = 4 + (X[:,0] - X[:,0].min()) / (X[:,0].max() - X[:,0].min()) * 6
Feature2 = 40 + (X[:,1] - X[:,1].min()) / (X[:,1].max() - X[:,1].min()) * 60

In [13]:
df = pd.DataFrame({
    "Feature1": Feature1,
    "Feature2": Feature2,
    "Class": y
})

df["Feature1"] = (df["Feature1"] - df["Feature1"].mean()) / df["Feature1"].std()
df["Feature2"] = (
    (df["Feature2"] - df["Feature2"].mean())
    / df["Feature2"].std()
)

df.head()

,Feature1,Feature2,Class
0,0.375501,-0.121659,1
1,0.263947,-1.814197,0
2,0.021507,-1.314660,0
3,-0.733024,0.144970,0
4,0.850220,1.130199,1


In [14]:
model = Sequential()

model.add(Dense(2,activation="sigmoid",input_dim=2))
model.add(Dense(1,activation="sigmoid"))

C:\Users\PC\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
new_weights = [
    np.array([[0.1,0.1],
              [0.1,0.1]], dtype=np.float32),

    np.array([0.,0.], dtype=np.float32),

    np.array([[0.1],
              [0.1]], dtype=np.float32),

    np.array([0.], dtype=np.float32)
]

model.set_weights(new_weights)

In [17]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
optimizer = keras.optimizers.Adam(learning_rate=0.3)

model.compile(loss="binary_crossentropy",optimizer=optimizer,metrics=["accuracy"])

In [19]:
history = model.fit(df.iloc[:,0:-1].values,df["placed"].values,epochs=100,batch_size=1,verbose=1)

KeyError: 'placed'

In [ ]:
model.get_weights()

[array([[-24.159866, -24.159866],
        [ -8.77632 ,  -8.77632 ]], dtype=float32),
 array([-0.7608812, -0.7608812], dtype=float32),
 array([[-5.5200033],
        [-5.5200033]], dtype=float32),
 array([7.96567], dtype=float32)]